# Generated by Django 6.0.1 on 2026-01-29 08:15

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="cta_primary_link",
            field=models.CharField(
                default="/study-guide/",
                help_text="Link for the primary CTA button",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_primary_text",
            field=models.CharField(
                default="Browse Study Guide",
                help_text="Text for the primary call-to-action button",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_secondary_link",
            field=models.CharField(
                default="/blog/",
                help_text="Link for the secondary CTA button",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_secondary_text",
            field=models.CharField(
                default="Read Our Blog",
                help_text="Text for the secondary call-to-action button",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_subtitle",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>Prepare for your next software engineering interview with our comprehensive study guides and expert insights.</p>",
                help_text="Subtitle text below the main headline",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(
                default="Master Technical Interviews",
                help_text="Main headline on the homepage",
                max_length=255,
            ),
        ),
    ]
